// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

// Load app/.env so DATABASE_URL from there overrides root .env (e.g. Neon URL)
config({ path: path.join(process.cwd(), "app", ".env"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
});
